### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by WeAthFoLD** [WeAthFoLD/SceneDemo#1]
Just a self reminder.

* [ ] Heightmap terrain generation
* [ ] Model loading & rendering
* [ ] Light model
* [ ] Various shadow techniques
